Stage1
Pyrus-vagus/CRM-webix-jet pull request #1
Opened 2021-09-03 11:43 UTC by Pyrus-vagus

Completed [stage1](https://hackmd.io/@listopad/ryCoimqkz?type=view) tasks

2021-09-06 10:29 UTC, kullias requested changes

2021-09-06 10:29 UTC, kullias commented on sources/views/contacts/contacts.js
> +      cols: [list, { $subview: "contacts.details" }],
можно и статически, оно не меняется

2021-09-06 10:29 UTC, kullias commented on sources/views/contacts/contacts.js
> +  urlChange() {
id будет меняться откуда-то вне этого вью? если нет, можно и в ините селект делать

2021-09-06 10:29 UTC, kullias commented on sources/views/activities/table.js
> +        onCheck: function (row, column, state) {
лишнее, отправляет еще один PUT запрос
вебикс логика сама его по чеку отправляет

2021-09-06 10:29 UTC, kullias commented on sources/views/activities/table.js
> +        onAfterSelect: (id) => {
пока что параметр этот никому не нужен тут, можно убрать, если дальше логика не будет им пользоваться

2021-09-06 10:29 UTC, kullias commented on sources/views/activities/table.js
> +      const id = this.getParam("id");
пока что параметр этот никому не нужен тут, можно убрать, если дальше логика не будет им пользоваться

2021-09-06 10:29 UTC, kullias commented on sources/views/activities/table.js
> +    activities.waitData.then(() => {
лучше одним промисом дождаться все три коллекции и потом запарсить. не стоит три раза рефрешить

2021-09-06 10:29 UTC, kullias commented on sources/views/activities/table.js
> +      this.$$("table").show(id);
showItem

2021-09-06 10:29 UTC, kullias commented on sources/views/activities/table.js
> +    this.win1 = this.ui(new EditForm(this.app, "Add", ""));
мб стоит одно окно создать только и в showPopup ему передавать строку

2021-09-06 10:33 UTC, kullias commented on sources/views/activities/form.js
> +      activities.waitSave(() => {
кажется  waitSave нам не нужен) сохранение инициируется операциями на коллекции

2021-09-06 10:46 UTC, kullias commented on sources/views/top.js
> +        { value: "Settings", id: "settings.settings", icon: "fas fa-cogs" },
contacts.contacts
settings.settings

=> index.js

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +      cols: [list, { $subview: "contacts.details" }],
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +  urlChange() {
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/activities/table.js
> +        onCheck: function (row, column, state) {
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/activities/table.js
> +        onAfterSelect: (id) => {
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/activities/table.js
> +      const id = this.getParam("id");
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/activities/table.js
> +    activities.waitData.then(() => {
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/activities/table.js
> +      this.$$("table").show(id);
Исправила

2021-09-07 08:01 UTC, Pyrus-vagus commented on sources/views/activities/table.js
> +    this.win1 = this.ui(new EditForm(this.app, "Add", ""));
Исправила

2021-09-07 08:02 UTC, Pyrus-vagus commented on sources/views/activities/form.js
> +      activities.waitSave(() => {
Исправила

2021-09-07 08:02 UTC, Pyrus-vagus commented on sources/views/top.js
> +        { value: "Settings", id: "settings.settings", icon: "fas fa-cogs" },
Исправила

2021-09-07 10:54 UTC, kullias commented on sources/views/activities/table.js
> +    activities.waitData.then(() => {
resfreshes are unnecessary
best save table ref to a constant

2021-09-07 11:07 UTC, kullias approved these changes

2021-09-28 15:54 UTC, merged